version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          name: Install Builder
          command : |
            gem install bundler            
      - run: 
          name: Link Bundle Path
          command : |
            bundle --path vendor/bundle
      - run:
          name: Precompile Assets
          command: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/setup-github.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
